/* AUTOGENERATED see generate_rom.py */
module rom (
    input clk,
                          
    input mem_valid,
    output reg mem_ready,
    input [31:0] mem_addr,                   
    output reg [31:0] mem_rdata,                   
    input [31:0] mem_wdata,
    input [3:0] mem_wstrb 
);
    localparam DEPTH = 8;
    localparam WORDS = 1 << DEPTH;

    reg [31:0] rom [0:WORDS-1];

    integer i;
    initial begin
        for(i = 0; i < WORDS; i = i + 1) rom[i] = 32'h00000000;
        rom[0] = 32'h00100213;
        rom[1] = 32'h00000293;
        rom[2] = 32'h00020313;
        rom[3] = 32'h00520233;
        rom[4] = 32'h00030293;
        rom[5] = 32'h00402023;
        rom[6] = 32'hff1ff06f;
    end

    always @(posedge clk) begin
        mem_ready <= 0;
        if(mem_valid && !mem_ready) begin
            mem_ready <= 1;
            mem_rdata <= rom[mem_addr >> 2];
        end
    end
endmodule
